// <auto-generated />
namespace CgData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class additemforeignkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additemforeignkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081008324_add item foreign keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
